pub fn linux_key_to_protocol_key(key: u32) ?pinput.Key {
    if (@import("builtin").os.tag != .linux) @compileError("Unsupported OS");

    return switch (key) {
        c_linux.KEY_0 => .zero,
        c_linux.KEY_1 => .one,
        c_linux.KEY_2 => .two,
        c_linux.KEY_3 => .three,
        c_linux.KEY_4 => .four,
        c_linux.KEY_5 => .five,
        c_linux.KEY_6 => .six,
        c_linux.KEY_7 => .seven,
        c_linux.KEY_8 => .eight,
        c_linux.KEY_9 => .nine,

        c_linux.KEY_A => .a,
        c_linux.KEY_B => .b,
        c_linux.KEY_C => .c,
        c_linux.KEY_D => .d,
        c_linux.KEY_E => .e,
        c_linux.KEY_F => .f,
        c_linux.KEY_G => .g,
        c_linux.KEY_H => .h,
        c_linux.KEY_I => .i,
        c_linux.KEY_J => .j,
        c_linux.KEY_K => .k,
        c_linux.KEY_L => .l,
        c_linux.KEY_M => .m,
        c_linux.KEY_N => .n,
        c_linux.KEY_O => .o,
        c_linux.KEY_P => .p,
        c_linux.KEY_Q => .q,
        c_linux.KEY_R => .r,
        c_linux.KEY_S => .s,
        c_linux.KEY_T => .t,
        c_linux.KEY_U => .u,
        c_linux.KEY_V => .v,
        c_linux.KEY_W => .w,
        c_linux.KEY_X => .x,
        c_linux.KEY_Y => .y,
        c_linux.KEY_Z => .z,

        c_linux.KEY_KP0 => .kp_0,
        c_linux.KEY_KP1 => .kp_1,
        c_linux.KEY_KP2 => .kp_2,
        c_linux.KEY_KP3 => .kp_3,
        c_linux.KEY_KP4 => .kp_4,
        c_linux.KEY_KP5 => .kp_5,
        c_linux.KEY_KP6 => .kp_6,
        c_linux.KEY_KP7 => .kp_7,
        c_linux.KEY_KP8 => .kp_8,
        c_linux.KEY_KP9 => .kp_9,

        c_linux.KEY_F1 => .f1,
        c_linux.KEY_F2 => .f2,
        c_linux.KEY_F3 => .f3,
        c_linux.KEY_F4 => .f4,
        c_linux.KEY_F5 => .f5,
        c_linux.KEY_F6 => .f6,
        c_linux.KEY_F7 => .f7,
        c_linux.KEY_F8 => .f8,
        c_linux.KEY_F9 => .f9,
        c_linux.KEY_F10 => .f10,
        c_linux.KEY_F11 => .f11,
        c_linux.KEY_F12 => .f12,
        c_linux.KEY_F13 => .f13,
        c_linux.KEY_F14 => .f14,
        c_linux.KEY_F15 => .f15,
        c_linux.KEY_F16 => .f16,
        c_linux.KEY_F17 => .f17,
        c_linux.KEY_F18 => .f18,
        c_linux.KEY_F19 => .f19,
        c_linux.KEY_F20 => .f20,
        c_linux.KEY_F21 => .f21,
        c_linux.KEY_F22 => .f22,
        c_linux.KEY_F23 => .f23,
        c_linux.KEY_F24 => .f24,

        c_linux.KEY_LEFTBRACE => .left_bracket,
        c_linux.KEY_RIGHTBRACE => .right_bracket,
        c_linux.KEY_LEFTCTRL => .left_control,
        c_linux.KEY_RIGHTCTRL => .right_control,
        c_linux.KEY_LEFTSHIFT => .left_shift,
        c_linux.KEY_RIGHTSHIFT => .right_shift,
        c_linux.KEY_LEFTALT => .left_alt,
        c_linux.KEY_RIGHTALT => .right_alt,
        c_linux.KEY_LEFTMETA => .left_gui,
        c_linux.KEY_RIGHTMETA => .right_gui,

        c_linux.KEY_UP => .up,
        c_linux.KEY_LEFT => .left,
        c_linux.KEY_RIGHT => .right,
        c_linux.KEY_DOWN => .down,

        c_linux.KEY_ESC => .escape,
        c_linux.KEY_MINUS => .minus,
        c_linux.KEY_EQUAL => .equal,
        c_linux.KEY_BACKSPACE => .backspace,
        c_linux.KEY_TAB => .tab,
        c_linux.KEY_ENTER => .enter,
        c_linux.KEY_INSERT => .insert,
        c_linux.KEY_DELETE => .delete,
        c_linux.KEY_SEMICOLON => .semicolon,
        c_linux.KEY_APOSTROPHE => .apostrophe,
        c_linux.KEY_GRAVE => .grave_accent,
        c_linux.KEY_BACKSLASH => .backslash,
        c_linux.KEY_COMMA => .comma,
        c_linux.KEY_SLASH => .slash,
        c_linux.KEY_DOT => .period,
        c_linux.KEY_SPACE => .space,
        c_linux.KEY_CAPSLOCK => .caps_lock,
        c_linux.KEY_NUMLOCK => .num_lock,
        c_linux.KEY_SCROLLLOCK => .scroll_lock,
        c_linux.KEY_KPMINUS => .kp_minus,
        c_linux.KEY_KPPLUS => .kp_plus,
        c_linux.KEY_KPENTER => .kp_enter,
        c_linux.KEY_HOME => .home,
        c_linux.KEY_END => .end,
        c_linux.KEY_PAGEUP => .page_up,
        c_linux.KEY_PAGEDOWN => .page_down,
        c_linux.KEY_MENU => .menu,

        else => null,
    };
}

const pinput = @import("protocol").input;
const c_linux = @import("c_linux");
