#include <stdio.h>
#include <sys/socket.h>
#include <EGL/egl.h>
#include <EGL/eglext.h>
#include <gbm.h>
#include <drm/drm_fourcc.h>
#include <xf86drm.h>
#include <errno.h>
#include <linux/input-event-codes.h>
#include <xkbcommon/xkbcommon.h>
